name: 'Run phpcs with reviewdog'
description: '🐶 Run phpcs with reviewdog on pull requests to improve code review experience.'
author: 'reflexxion'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].
      Default is github-pr-check.
      github-pr-review can use Markdown and add a link to rule page in reviewdog reports.
    default: 'github-pr-check'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false]
      Default is `false`.
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags'
    default: ''
  memory_limit:
    description: |
      set the php memory_limit for phpcs
      Default is `128m`.
    default: '128m'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zoom-in'
  color: 'purple'