name: Create Release
on:
    push:
        branches:
            - main

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.inputs.ref }}
            - name: Conventional Changelog Action
              id: changelog
              uses: TriPSs/conventional-changelog-action@v3
              with:
                  github-token: ${{ github.token }}
                  preset: conventionalcommits
                  skip-version-file: true
                  skip-on-empty: false
                  release-count: 0
                  fallback-version: '1.0.0'
            - name: Create Release
              uses: actions/create-release@v1
              if: ${{ steps.changelog.outputs.skipped == 'false' }}
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  tag_name: ${{ steps.changelog.outputs.tag }}
                  release_name: ${{ steps.changelog.outputs.tag }}
                  body: ${{ steps.changelog.outputs.clean_changelog }}
